# conda env create --file environment.yml
name: ejercicios_python
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - fs
  - jupyter
  - jupyterlab
  - pathlib
  - pip
  - pyprojroot
  - python=3.12
  - pip:
    - pyhere
    